### ISSUE TITLE
Develop standard arithmetic function

### ISSUE THREAD

**Issue by NPLeeWenKang** [DevOps-Team-C-2022/DevOps_Oct2022_TeamC#11]
**Description**
Creation of arithmetic functions and menu which include addition subtraction division and multiplication.

**Requirements**
- [x] Add 2 numbers
- [x] Subtract 2 numbers
- [x] Multiply 2 numbers
- [x] Delete 2 numbers

**Definition of done**
- The right results are returned 
- Errors should be displayed

**Approach**
1. Create a menu for the users to select which function they would like to use
2. Request users for inputs for the values they want to manupilate 
3.  Include the appropirate mathimatical formulas to the different functions 

**Pull Requests*
1. https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/pull/30

**Comment by chuadongen** [comment]
LGTM
