### ISSUE TITLE
Develop trigonometry function

### ISSUE THREAD

**Issue by NPLeeWenKang** [DevOps-Team-C-2022/DevOps_Oct2022_TeamC#12]
**Description**
When user select trigonometry function, the user should be able to calculate trigo and inverse trigo functions.

**Requirements**

- [x] Sin
- [x] Cos
- [x] Tan
- [x] Sin-1
- [x] Cos-1
- [x] Tan-1

**Definition of done**

- [x] Same output as calculator
- [x] Answer in degree

**Approach**
1. Import math -> math.sin(num) ...

**Pull Requests**
1. https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/pull/27

**Comment by chuadongen** [comment]
LGTM
