### ISSUE TITLE
Develop exponents function (power of X)

### ISSUE THREAD

**Issue by Balqiskinanti** [DevOps-Team-C-2022/DevOps_Oct2022_TeamC#14]
**Description**
After user selects exponent function, allow them to multiply a number by an exponent number

**Requirements**
- [x]  Calculate exponent functions. (base ** exponent)
- [x]  Error checking when non-integer is used.

**Definition of done**
- [x]  Error is checked.
- [x]  Calculation is accurate

**Pull Request**

1. https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/pull/26

**Comment by chuadongen** [comment]
LGTM
