### ISSUE TITLE
Develop square root function

### ISSUE THREAD

**Issue by Balqiskinanti** [DevOps-Team-C-2022/DevOps_Oct2022_TeamC#15]
**Description**
When the user selects to do square root funtion, the system should prompt the user for the values he wishes to square root and return the value

**Requirements**
- [x]  Allow the user to enter a number and return the square root

**Definition of done**
- [x] Input: 4 Result:2

**Approach**
1. Write a function and integrate with menu from  https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/issues/20

**Pull Requests**
1. https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/pull/29/files#diff-1394800a49701c2a9c03e05ac90f745ec29daef260e56ecd9f47a96d5b19d0a8

**Comment by chuadongen** [comment]
LGTM, integrated with https://github.com/DevOps-Team-C-2022/DevOps_Oct2022_TeamC/issues/20
